services:
  - type: web
    name: shl-recommender-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt && python -m utils.preprocess
    startCommand: cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000

